kind: pipeline
type: docker
name: Anki Builder

platform:
  os: linux
  arch: arm64

environment:
  ANKI_VER: 2.1.42

steps:
- name: Build Anki
  image: fedora
  settings:
    tags: 34
  commands:
  - bash build.sh
  - tar -cf anki.tar.xz .
    
- name: Publish
  image: plugins/github-release
  settings:
   api_key: 
     from_secret: Github
   files: anki.tar.xz
   checksum:
   - sha256
  when:
   event:
   - tag
