kind: pipeline
type: docker
name: Anki Builder

platform:
  os: linux
  arch: arm64

steps:
- name: Build Anki
  image: fedora
  settings:
    tags: 34
  commands:
  - bash build.sh
    
- name: Publish
  image: plugins/github-release
  settings:
    api_key: 
      from_secret: Github
    files:
      - bazel-bin/dist.tar
   checksum:
      - sha256
  when:
   event:
   - promote
   target:
   - production
