kind: pipeline
type: docker
name: Anki Fedora Builder

platform:
  os: linux
  arch: arm64

environment:
  ANKI_VER: 2.1.43

steps:
- name: Build Anki Fedora
  image: fedora:34
  commands:
  - bash build-fedora.sh
  - tar -cf anki-fedora.tar.xz .
    
- name: Publish
  image: plugins/github-release
  settings:
   api_key: 
     from_secret: Github
   files: anki-fedora.tar.xz
   checksum:
   - sha256
  when:
   event:
   - tag

---
kind: pipeline
type: docker
name: Anki Ubuntu Builder

platform:
  os: linux
  arch: arm64

environment:
  ANKI_VER: 2.1.43

steps:
- name: Build Anki Ubuntu
  image: ubuntu:21.04
  commands:
  - bash build-ubuntu.sh
  - tar -cf anki-ubuntu.tar.xz .
    
- name: Publish
  image: plugins/github-release
  settings:
   api_key: 
     from_secret: Github
   files: anki-ubuntu.tar.xz
   checksum:
   - sha256
  when:
   event:
   - tag