kind: pipeline
type: docker
name: Anki Builder

platform:
  os: linux
  arch: arm64

environment:
  ANKI_VER: 2.1.41

steps:
- name: Build Anki
  image: fedora
  settings:
    tags: 34
  commands:
  - bash build.sh
    
- name: Publish
  image: plugins/github-release
  settings:
   api_key: 
     from_secret: Github
   files: ./*
   checksum:
   - sha256
  when:
   event:
   - tag
